### ISSUE TITLE
task xlsx-to-oscal-component-definition 2 bugs

### ISSUE THREAD

**Issue by degenaro** [IBM/compliance-trestle#1016]
## Describe the bug

task xlsx-to-oscal-component-definition has 2 bugs:
1. the directory to contain the emitted parameters catalog may not exist
2. the column AS of the input sheet sheet with an invalid entry should cause a message not an abort

## To Reproduce

1. run the trestle task xlsx-to-oscal-component-definition with a config comprising a non-existent parameters catalog directory
2. run the trestle task xlsx-to-oscal-component-definition with a config comprising a spread sheet with at least on AS column having a value that does not conform to < description /n parameter_name >

## Expected behavior

1. the directory should be automatically created
2. a message should be emitted but the task should carry on

## Screenshots / Logs.

```
Traceback (most recent call last):
  File "/home/degenaro/git/compliance-trestle.develop/trestle/tasks/xlsx_to_oscal_component_definition.py", line 156, in execute
    return self._execute()
  File "/home/degenaro/git/compliance-trestle.develop/trestle/tasks/xlsx_to_oscal_component_definition.py", line 282, in _execute
    self._write_catalog()
  File "/home/degenaro/git/compliance-trestle.develop/trestle/tasks/xlsx_to_oscal_component_definition.py", line 559, in _write_catalog
    self.parameter_helper.write_parameters_catalog(
  File "/home/degenaro/git/compliance-trestle.develop/trestle/tasks/xlsx_to_oscal_component_definition.py", line 861, in write_parameters_catalog
    parameter_catalog.oscal_write(pathlib.Path(ofile))
  File "/home/degenaro/git/compliance-trestle.develop/trestle/core/base_model.py", line 275, in oscal_write
    write_file = pathlib.Path(path).open('wb')
  File "/usr/local/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/local/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/degenaro/git/shared-trestle-workspace/catalogs/ibm-best-practices/catalog.json'
```
```
Traceback (most recent call last):
  File "/home/degenaro/git/compliance-trestle.develop/trestle/tasks/xlsx_to_oscal_component_definition.py", line 156, in execute
    return self._execute()
  File "/home/degenaro/git/compliance-trestle.develop/trestle/tasks/xlsx_to_oscal_component_definition.py", line 235, in _execute
    parameter_name, parameter_description = self._get_parameter_name_and_description(work_sheet, row)
  File "/home/degenaro/git/compliance-trestle.develop/trestle/tasks/xlsx_to_oscal_component_definition.py", line 696, in _get_parameter_name_and_description
    raise RuntimeError(f'row {row} col {col} unable to parse')
RuntimeError: row 231 col AS unable to parse
```

## Environment

- OS: rhel8
- Python version: 3.9.9
- Installed packages: trestle v0.34.0

**Comment by degenaro** [comment]
Fixed.
