### ISSUE TITLE
trestle task csv-to-oscal-cd cannot handle whitespace

### ISSUE THREAD

**Issue by HerbBoy** [IBM/compliance-trestle#1247]
## Describe the bug

Firstly, I only tested this with the **Rule_Description** column.

Issue: The **Rule_Description** column cannot handle whitespace. Whether it is the "start of the line" or "end of the line". 

## To Reproduce

1. Download: [example_invalid.csv](https://github.com/IBM/compliance-trestle/files/10014807/example_invalid.csv)
1. `cd to ~/trestle/valid_dir_struc`
1. `trestle task -v csv-to-oscal-cd -c ~/csv-to-oscal.config`
1. See error

## Expected behavior

For the regex to handle whitespace appropriately

## Screenshots / Logs.

Whitespace at SOL
```BASH
$ trestle task -v csv-to-oscal-cd -c ~/csv-to-oscal.config
trestle.core.commands.task:95 DEBUG: Loading task: csv-to-oscal-cd
input: /tmp/example_invalid.csv
trestle.tasks.csv_helper:226 DEBUG: 1 ['xccdf_org.ssgproject.content_rule_package_aide_installed', ' The AIDE package must be installed if it is to be available for integrity checking.', 'https://github.com/ComplianceAsCode/content/blob/master/products/rhel8/profiles/stig.profile', 'rhel8', 'Software', 'SI-6', 'OM', 'vm', '', '', '', '', '', '', '', '']
trestle.tasks.csv_to_oscal_cd:163 DEBUG: created component: OM:Software
trestle.tasks.csv_to_oscal_cd:189 DEBUG: created control implementation: OM:Software:rhel8
trestle.tasks.csv_to_oscal_cd:301 DEBUG: created implemented requirement: OM:Software:SI-6
trestle.tasks.csv_to_oscal_cd:203 DEBUG: row_num: 0 col: Rule_Id value: xccdf_org.ssgproject.content_rule_package_aide_installed
trestle.tasks.csv_to_oscal_cd:203 DEBUG: row_num: 0 col: Rule_Description value:  The AIDE package must be installed if it is to be available for integrity checking.
trestle.tasks.csv_to_oscal_cd:93 ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/trestle/tasks/csv_to_oscal_cd.py", line 91, in execute
    return self._execute()
  File "/usr/local/lib/python3.9/site-packages/trestle/tasks/csv_to_oscal_cd.py", line 120, in _execute
    self._process_rows()
  File "/usr/local/lib/python3.9/site-packages/trestle/tasks/csv_to_oscal_cd.py", line 361, in _process_rows
    self._add_rule_definition(row_num, row)
  File "/usr/local/lib/python3.9/site-packages/trestle/tasks/csv_to_oscal_cd.py", line 265, in _add_rule_definition
    self._create_rule_prop(row_num, control_implementation, row, column_name, ns, remarks)
  File "/usr/local/lib/python3.9/site-packages/trestle/tasks/csv_to_oscal_cd.py", line 208, in _create_rule_prop
    prop = Property(
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Property
value
  string does not match regex "^\S(.*\S)?$" (type=value_error.str.regex; pattern=^\S(.*\S)?$)

trestle.core.commands.task:96 ERROR: Error while executing Trestle task: Task csv-to-oscal-cd reported a TaskOutcome.FAILURE
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/trestle/core/commands/task.py", line 116, in _run
    raise TrestleError(f'Task {args.task} reported a {actual_result}')
trestle.common.err.TrestleError: Task csv-to-oscal-cd reported a TaskOutcome.FAILURE
```
Whitespace at EOL
```
$ trestle task -v csv-to-oscal-cd -c ~/csv-to-oscal.config
trestle.core.commands.task:95 DEBUG: Loading task: csv-to-oscal-cd
input: /tmp/example_invalid.csv
trestle.tasks.csv_helper:226 DEBUG: 1 ['xccdf_org.ssgproject.content_rule_package_aide_installed', 'The AIDE package must be installed if it is to be available for integrity checking.', 'https://github.com/ComplianceAsCode/content/blob/master/products/rhel8/profiles/stig.profile', 'rhel8', 'Software', 'SI-6', 'OM', 'vm', '', '', '', '', '', '', '', '']
trestle.tasks.csv_to_oscal_cd:163 DEBUG: created component: OM:Software
trestle.tasks.csv_to_oscal_cd:189 DEBUG: created control implementation: OM:Software:rhel8
trestle.tasks.csv_to_oscal_cd:301 DEBUG: created implemented requirement: OM:Software:SI-6
trestle.tasks.csv_to_oscal_cd:203 DEBUG: row_num: 0 col: Rule_Id value: xccdf_org.ssgproject.content_rule_package_aide_installed
trestle.tasks.csv_to_oscal_cd:203 DEBUG: row_num: 0 col: Rule_Description value: The AIDE package must be installed if it is to be available for integrity checking.
trestle.tasks.csv_to_oscal_cd:203 DEBUG: row_num: 0 col: Check_Id value:
trestle.tasks.csv_to_oscal_cd:203 DEBUG: row_num: 0 col: Check_Description value:
trestle.tasks.csv_to_oscal_cd:203 DEBUG: row_num: 0 col: Fetcher value:
trestle.tasks.csv_to_oscal_cd:203 DEBUG: row_num: 0 col: Fetcher_Description value:
trestle.tasks.csv_to_oscal_cd:203 DEBUG: row_num: 0 col: Resource_Instance_Type value: vm
trestle.tasks.csv_to_oscal_cd:227 DEBUG: 0 OM:Software:xccdf_org.ssgproject.content_rule_package_aide_installed [Property(name='Rule_Id', uuid=None, ns=None, value='xccdf_org.ssgproject.content_rule_package_aide_installed', class_=None, remarks=Remarks(__root__='rule_set_0')), Property(name='Rule_Description', uuid=None, ns=None, value='The AIDE package must be installed if it is to be available for integrity checking.', class_=None, remarks=Remarks(__root__='rule_set_0')), Property(name='Resource_Instance_Type', uuid=None, ns=None, value='vm', class_=None, remarks=Remarks(__root__='rule_set_0'))]
trestle.tasks.csv_helper:226 DEBUG: 2 ['xccdf_org.ssgproject.content_rule_aide_check_audit_tools', 'The operating system file integrity tool must be configured to protect the integrity of the audit tools.  ', 'https://github.com/ComplianceAsCode/content/blob/master/products/rhel8/profiles/stig.profile', 'rhel8', 'Software', 'AU-9', 'OM', 'vm', '', '', '', '', '', '', '', '']
trestle.tasks.csv_to_oscal_cd:301 DEBUG: created implemented requirement: OM:Software:AU-9
trestle.tasks.csv_to_oscal_cd:203 DEBUG: row_num: 1 col: Rule_Id value: xccdf_org.ssgproject.content_rule_aide_check_audit_tools
trestle.tasks.csv_to_oscal_cd:203 DEBUG: row_num: 1 col: Rule_Description value: The operating system file integrity tool must be configured to protect the integrity of the audit tools.
trestle.tasks.csv_to_oscal_cd:93 ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/trestle/tasks/csv_to_oscal_cd.py", line 91, in execute
    return self._execute()
  File "/usr/local/lib/python3.9/site-packages/trestle/tasks/csv_to_oscal_cd.py", line 120, in _execute
    self._process_rows()
  File "/usr/local/lib/python3.9/site-packages/trestle/tasks/csv_to_oscal_cd.py", line 361, in _process_rows
    self._add_rule_definition(row_num, row)
  File "/usr/local/lib/python3.9/site-packages/trestle/tasks/csv_to_oscal_cd.py", line 265, in _add_rule_definition
    self._create_rule_prop(row_num, control_implementation, row, column_name, ns, remarks)
  File "/usr/local/lib/python3.9/site-packages/trestle/tasks/csv_to_oscal_cd.py", line 208, in _create_rule_prop
    prop = Property(
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Property
value
  string does not match regex "^\S(.*\S)?$" (type=value_error.str.regex; pattern=^\S(.*\S)?$)

trestle.core.commands.task:96 ERROR: Error while executing Trestle task: Task csv-to-oscal-cd reported a TaskOutcome.FAILURE
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/trestle/core/commands/task.py", line 116, in _run
    raise TrestleError(f'Task {args.task} reported a {actual_result}')
trestle.common.err.TrestleError: Task csv-to-oscal-cd reported a TaskOutcome.FAILURE
```
## Environment

- OS: Rocky8
- Python version: Python 3.9.7
- Installed packages: trestle was pip installed. Dependencies were all met/installed.
- Severity: Low

**Comment by degenaro** [comment]
Fixed & merged into develop branch.
