### ISSUE TITLE
Python 3.11 Compatibllity: "ValueError: mutable default <class 'trestle.oscal.common.ImplementationStatus'> for field status is not allowed: use default_factory"

### ISSUE THREAD

**Issue by asaba-hashi** [IBM/compliance-trestle#1295]
## Describe the bug

The trestle commmand fails with the following strack trace with python 3.11.2, but works fine with 3.10.  A quick google made this seem like a common problem with 3.11 being pickier about this:

```
~/p/c/scratch2 ❯❯❯ pipenv shell
Launching subshell in virtual environment...
 . /Users/antonysaba/.local/share/virtualenvs/scratch2-JmL_IQ3d/bin/activate
~/p/c/scratch2 ❯❯❯  . /Users/antonysaba/.local/share/virtualenvs/scratch2-JmL_IQ3d/bin/activate
(scratch2) ~/p/c/scratch2 ❯❯❯ trestle -h
Traceback (most recent call last):
  File "/Users/antonysaba/.local/share/virtualenvs/scratch2-JmL_IQ3d/bin/trestle", line 5, in <module>
    from trestle.cli import run
  File "/Users/antonysaba/.local/share/virtualenvs/scratch2-JmL_IQ3d/lib/python3.11/site-packages/trestle/cli.py", line 24, in <module>
    from trestle.core.commands.assemble import AssembleCmd
  File "/Users/antonysaba/.local/share/virtualenvs/scratch2-JmL_IQ3d/lib/python3.11/site-packages/trestle/core/commands/assemble.py", line 23, in <module>
    from trestle.common.load_validate import load_validate_model_path
  File "/Users/antonysaba/.local/share/virtualenvs/scratch2-JmL_IQ3d/lib/python3.11/site-packages/trestle/common/load_validate.py", line 27, in <module>
    from trestle.core.validator_factory import validator_factory
  File "/Users/antonysaba/.local/share/virtualenvs/scratch2-JmL_IQ3d/lib/python3.11/site-packages/trestle/core/validator_factory.py", line 21, in <module>
    from trestle.core import all_validator, catalog_validator, duplicates_validator, links_validator, refs_validator
  File "/Users/antonysaba/.local/share/virtualenvs/scratch2-JmL_IQ3d/lib/python3.11/site-packages/trestle/core/catalog_validator.py", line 21, in <module>
    from trestle.core.catalog_interface import CatalogInterface
  File "/Users/antonysaba/.local/share/virtualenvs/scratch2-JmL_IQ3d/lib/python3.11/site-packages/trestle/core/catalog_interface.py", line 24, in <module>
    import trestle.core.generic_oscal as generic
  File "/Users/antonysaba/.local/share/virtualenvs/scratch2-JmL_IQ3d/lib/python3.11/site-packages/trestle/core/generic_oscal.py", line 27, in <module>
    from trestle.core.control_interface import ControlInterface
  File "/Users/antonysaba/.local/share/virtualenvs/scratch2-JmL_IQ3d/lib/python3.11/site-packages/trestle/core/control_interface.py", line 48, in <module>
    @dataclass
     ^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1220, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1210, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'trestle.oscal.common.ImplementationStatus'> for field status is not allowed: use default_factory
```

## To Reproduce

1. `pipenv --python 3.11 install compliance-trestle`
1. `pipenv shell`
1. `trestle -h`
1. See error

## Expected behavior

The command should run and `-h` text displayed.

## Environment

- OS: macOS Ventura
- Python version: python 3.11, installed via brew
- Installed packages:

**Comment by fsuits** [comment]
@asaba-hashi thank you for the report.  This is a known issue that has already been addressed in the develop branch, but I now realize the trestle github page is not explicit about the fact that we only support 3.7, 3.8, 3.9.  So I will create an issue to be more clear about this.  It is mentioned in the instructions for installing trestle, but the main page suggests we support 3.7+ and we will change that accordingly.

For now please use 3.9 and/or switch to the develop branch.
