### ISSUE TITLE
task csv-to-oscal-cd issues cryptic error message when processing invalid property value

### ISSUE THREAD

**Issue by degenaro** [IBM/compliance-trestle#1457]
## Describe the bug

Example error message:

```
trestle task csv-to-oscal-cd -c data/trestle/cd-fedramp-soc2.config
input: data/csv/test.csv
trestle.tasks.csv_to_oscal_cd:225 ERROR: Traceback (most recent call last):
  File "/tmp/venv.demos/lib/python3.9/site-packages/trestle/tasks/csv_to_oscal_cd.py", line 223, in execute
    return self._execute()
  File "/tmp/venv.demos/lib/python3.9/site-packages/trestle/tasks/csv_to_oscal_cd.py", line 262, in _execute
    self.rules_add(rules[1])
  File "/tmp/venv.demos/lib/python3.9/site-packages/trestle/tasks/csv_to_oscal_cd.py", line 490, in rules_add
    component.props = component.props + self._create_rule_props(rule_key)
  File "/tmp/venv.demos/lib/python3.9/site-packages/trestle/tasks/csv_to_oscal_cd.py", line 562, in _create_rule_props
    rule_set_mgr.add_prop(prop_name, prop_value, namespace, self.get_class(prop_name))
  File "/tmp/venv.demos/lib/python3.9/site-packages/trestle/tasks/csv_to_oscal_cd.py", line 906, in add_prop
    prop = Property(
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Property
value
  string does not match regex "^\S(.*\S)?$" (type=value_error.str.regex; pattern=^\S(.*\S)?$)

trestle.core.commands.task:94 ERROR: Error while executing Trestle task: Task csv-to-oscal-cd reported a TaskOutcome.FAILURE
make: *** [Makefile:23: cd-csv-to-json] Error 1
```

## To Reproduce

Run trestle trestle task csv-to-oscal-cd using .csv file containing non-string OSCAL data type for rule property.

## Expected behavior

A better error message indicating the property name a value should be emitted.

## Screenshots / Logs.

See above.

## Environment

- OS: Red Hat 8.8
- Python version: 3.9
- Installed packages: compliance-trestle

**Comment by degenaro** [comment]
Fixed by #1459
