### ISSUE TITLE
Dict's of UUID:object cause problems for trestle add.

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#217]
**Describe the bug**
trestle add -f component-definition.json -e component-definition.components.component 
Traceback (most recent call last):
  File "/Users/chris/opt/anaconda3/bin/trestle", line 33, in <module>
    sys.exit(load_entry_point('compliance-trestle', 'console_scripts', 'trestle')())
  File "/Users/chris/go/src/github.com/IBM/compliance-trestle/trestle/cli.py", line 52, in run
    exit(Trestle().run())
  File "/Users/chris/opt/anaconda3/lib/python3.7/site-packages/ilcli/command.py", line 147, in run
    return parsed_args.func(parsed_args, extra_args=extra_args)
  File "/Users/chris/opt/anaconda3/lib/python3.7/site-packages/ilcli/command.py", line 174, in _validate_and_run
    return self._run(parsed_args)
  File "/Users/chris/go/src/github.com/IBM/compliance-trestle/trestle/core/commands/add.py", line 74, in _run
    update_action, parent_element = self.add(element_path, parent_model, parent_element)
  File "/Users/chris/go/src/github.com/IBM/compliance-trestle/trestle/core/commands/add.py", line 125, in add
    parent_element = parent_element.set_at(element_path, child_object)
  File "/Users/chris/go/src/github.com/IBM/compliance-trestle/trestle/core/models/elements.py", line 354, in set_at
    of type "{model_obj.__class__}"'
trestle.core.err.TrestleError: Element "<class 'dict'>" does not have the attribute "component"                     of type "<class 'trestle.oscal.component.Component'>"

**Comment by butler54** [comment]
I'm not sure where we reached on this issue.
