### ISSUE TITLE
Trestle init has a dependency issue on OSX causing a ttraceback.

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#239]
**Describe the bug**
Running trestle init against python 3.7 on a mac is causing issues.

```
trestle init 
Traceback (most recent call last):
  File "/Users/chris/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/Users/chris/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/chris/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (importlib-metadata 3.0.0 (/Users/chris/opt/anaconda3/lib/python3.7/site-packages), Requirement.parse('importlib-metadata<3,>=0.23; python_version == "3.7"'), {'argcomplete'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chris/opt/anaconda3/bin/trestle", line 33, in <module>
    sys.exit(load_entry_point('compliance-trestle', 'console_scripts', 'trestle')())
  File "/Users/chris/opt/anaconda3/bin/trestle", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/chris/opt/anaconda3/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 93, in load
    module = import_module(match.group('module'))
  File "/Users/chris/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/chris/go/src/github.com/IBM/compliance-trestle/trestle/cli.py", line 24, in <module>
    from trestle.core.commands.init import InitCmd
  File "/Users/chris/go/src/github.com/IBM/compliance-trestle/trestle/core/commands/init.py", line 23, in <module>
    from pkg_resources import resource_filename
  File "/Users/chris/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3238, in <module>
    @_call_aside
  File "/Users/chris/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/Users/chris/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/chris/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 569, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/chris/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 582, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/chris/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'importlib-metadata<3,>=0.23; python_version == "3.7"' distribution was not found and is required by argcomplete
(base) chris@jettopper trestle_test_2 % trestle init       
Traceback (most recent call last):
  File "/Users/chris/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/Users/chris/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/chris/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (importlib-metadata 3.1.0 (/Users/chris/opt/anaconda3/lib/python3.7/site-packages), Requirement.parse('importlib-metadata<3,>=0.23; python_version == "3.7"'), {'argcomplete'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chris/opt/anaconda3/bin/trestle", line 33, in <module>
    sys.exit(load_entry_point('compliance-trestle', 'console_scripts', 'trestle')())
  File "/Users/chris/opt/anaconda3/bin/trestle", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/chris/opt/anaconda3/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 93, in load
    module = import_module(match.group('module'))
  File "/Users/chris/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/chris/go/src/github.com/IBM/compliance-trestle/trestle/cli.py", line 24, in <module>
    from trestle.core.commands.init import InitCmd
  File "/Users/chris/go/src/github.com/IBM/compliance-trestle/trestle/core/commands/init.py", line 23, in <module>
    from pkg_resources import resource_filename
  File "/Users/chris/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3238, in <module>
    @_call_aside
  File "/Users/chris/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/Users/chris/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/chris/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 569, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/chris/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 582, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/chris/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'importlib-metadata<3,>=0.23; python_version == "3.7"' distribution was not found and is required by argcomplete
```
It is unknown as to why this is not getting picked up during testing on a mac in CICD.

**Comment by butler54** [comment]
This appears to be have been a transient issue with dependencies. Closing for now.
