### ISSUE TITLE
If a bad file extension is given to Trestle remove, the resulting error should be handled neatly

### ISSUE THREAD

**Issue by jeffdmgit** [IBM/compliance-trestle#244]
When a bad file extension is supplied to **trestle remove -f**, it throws out a messy exception:

    $ trestle remove -f minimal_catalog.yam -e catalog.metadata.responsible-parties.organisation.party-uuids
    Traceback (most recent call last):
      File "/Users/jeffetan/anaconda3/envs/trestle/bin/trestle", line 33, in <module>
        sys.exit(load_entry_point('compliance-trestle', 'console_scripts', 'trestle')())
      File "/Users/jeffetan/Git/src/github.com/IBM/compliance-trestle/trestle/cli.py", line 52, in run
        exit(Trestle().run())
      File "/Users/jeffetan/anaconda3/envs/trestle/lib/python3.8/site-packages/ilcli/command.py", line 147, in run
        return parsed_args.func(parsed_args, extra_args=extra_args)
      File "/Users/jeffetan/anaconda3/envs/trestle/lib/python3.8/site-packages/ilcli/command.py", line 174, in _validate_and_run
        return self._run(parsed_args)
      File "/Users/jeffetan/Git/src/github.com/IBM/compliance-trestle/trestle/core/commands/remove.py", line 76, in _run
        parent_object = parent_model.oscal_read(file_path.absolute())
      File "/Users/jeffetan/Git/src/github.com/IBM/compliance-trestle/trestle/core/base_model.py", line 199, in oscal_read
        content_type = FileContentType.to_content_type(path.suffix)
      File "/Users/jeffetan/Git/src/github.com/IBM/compliance-trestle/trestle/core/models/file_content_type.py", line 47, in to_content_type
        raise TrestleError(f'Unsupported file extension {file_extension}')
    trestle.core.err.TrestleError: Unsupported file extension .yam
    $

## Completion Criteria
Throw back cleaner complaints, instead, e.g.,

    $ trestle add -f minimal_catalog.txt -e catalog.metadata.responsible-parties
    Add failed: Unsupported file extension .txt

## Steps to Reproduce the Problem

1. Call **trestle remove -f** with a file argument whose extension is not supported, e.g., '.txt'.
1. See the same messy complaint as above.

## Specifications

- Version / branch: develop (commit #a09e192b8a9ed2e8ccf362b38b4f9b2aecef54cd)
- Platform: MacOS 11.0.1

**Comment by jeffdmgit** [comment]
Now that I think about it, where does a user find out which file extensions are accepted? Should this information be given in the complaint about the unsupported extension?
