### ISSUE TITLE
improve handling of unsupported file extensions for trestle split

### ISSUE THREAD

**Issue by jeffdmgit** [IBM/compliance-trestle#248]
**Describe the bug**
When **trestle split -f** is given a file with an unsupported file extension, e.g., *.txt*, it raises an exception and exits with messy complaints.

**To Reproduce**
1. On the *develop* branch, invoke **trestle split -f** and supply a file argument with an unsupported file extension, e.g., *.txt*.
1. Error comes back as below.

**Expected behavior**
A cleaner error message should be returned instead. 

**CLI session**

    $ trestle split -f catalogs/minimal_catalog/metadata.txt -e metadata.responsible-parties
    Traceback (most recent call last):
      File "/Users/jeffetan/anaconda3/envs/trestle/bin/trestle", line 33, in <module>
        sys.exit(load_entry_point('compliance-trestle', 'console_scripts', 'trestle')())
      File "/Users/jeffetan/Git/src/github.com/IBM/compliance-trestle/trestle/cli.py", line 52, in run
        exit(Trestle().run())
      File "/Users/jeffetan/anaconda3/envs/trestle/lib/python3.8/site-packages/ilcli/command.py", line 147, in run
        return parsed_args.func(parsed_args, extra_args=extra_args)
      File "/Users/jeffetan/anaconda3/envs/trestle/lib/python3.8/site-packages/ilcli/command.py", line 174, in _validate_and_run
        return self._run(parsed_args)
      File "/Users/jeffetan/Git/src/github.com/IBM/compliance-trestle/trestle/core/commands/split.py", line 60, in _run
        content_type = FileContentType.to_content_type(file_path.suffix)
      File "/Users/jeffetan/Git/src/github.com/IBM/compliance-trestle/trestle/core/models/file_content_type.py", line 47, in to_content_type
        raise TrestleError(f'Unsupported file extension {file_extension}')
    trestle.core.err.TrestleError: Unsupported file extension .txt

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 11.0.1

**Comment by butler54** [comment]
I think this should be a relatively simple error handling to do.

**Comment by fsuits** [comment]
With recent [PR 489](https://github.com/IBM/compliance-trestle/pull/489) this now yields:

(trestle3) c:\tmp\test10\catalogs\mycatalog>trestle split -f catalog.txt -e catalog.metadata
WARNING:root:Unsupported file extension .txt
