### ISSUE TITLE
Splitting roles collection fails 

### ISSUE THREAD

**Issue by deenine** [IBM/compliance-trestle#548]
**Describe the bug**
The [tutorial](https://ibm.github.io/compliance-trestle/tutorials/trestle_sample_workflow/#tutorial-introduction-to-trestle-workflow) describes the process of splitting `roles.json` into separate roles, however [step 5](https://ibm.github.io/compliance-trestle/tutorials/trestle_sample_workflow/#step-5-split-metadata-further-using-wildcards) `trestle split -f ./roles.json -e 'roles.*'` fails due to lack of a wrapper_alias: `WARNING:root:wrapper_alias is required for a collection type object`.

This can be avoided by specifying `wrapper_alias=Element.IGNORE_WRAPPER_ALIAS` when creating the Element object on line 185 in `trestle/core/commands/split.py`:
`element = Element(model_obj, wrapper_alias=Element.IGNORE_WRAPPER_ALIAS)`

However, this seems like an issue with either the input data, or in the assumptions trestle makes around the content of the input data.

Full debug trace:
```
(.venv_trestle) ~/workspace/compliance-trestle/trestle.workspace/catalogs/mycatalog/catalog/metadata $trestle split -v -f ./roles.json -e 'roles.*'
2021-05-27 10:16:12,839 trestle.utils.fs:161 DEBUG: get_stripped_contextual_model path is /Users/deenine/workspace/compliance-trestle/trestle.workspace/catalogs/mycatalog/catalog/metadata/roles.json and not stripped is None
2021-05-27 10:16:12,839 trestle.utils.fs:104 DEBUG: get contextual model type for input path /Users/deenine/workspace/compliance-trestle/trestle.workspace/catalogs/mycatalog/catalog/metadata/roles.json
2021-05-27 10:16:12,839 trestle.utils.fs:111 DEBUG: get contextual model type final path /Users/deenine/workspace/compliance-trestle/trestle.workspace/catalogs/mycatalog/catalog/metadata/roles.json
2021-05-27 10:16:12,840 trestle.utils.fs:119 DEBUG: root_path is /Users/deenine/workspace/compliance-trestle/trestle.workspace and project_model_path is /Users/deenine/workspace/compliance-trestle/trestle.workspace/catalogs/mycatalog
2021-05-27 10:16:12,840 trestle.utils.fs:166 DEBUG: singular model type <class 'types.ConstrainedListValue'> model alias catalog.metadata.roles
2021-05-27 10:16:12,840 trestle.utils.fs:173 DEBUG: collection field type class name Roles and alias roles
2021-05-27 10:16:12,841 trestle.utils.fs:175 DEBUG: model_type created: <class 'pydantic.main.Roles'>
2021-05-27 10:16:12,841 trestle.core.base_model:277 DEBUG: oscal_read content type FileContentType.JSON and alias roles from /Users/deenine/workspace/compliance-trestle/trestle.workspace/catalogs/mycatalog/catalog/metadata/roles.json
2021-05-27 10:16:12,841 trestle.core.commands.split:100 DEBUG: split calling parse_element_args on roles.*
2021-05-27 10:16:12,841 trestle.utils.fs:266 DEBUG: get_singular_alias contextual mode: <class 'str'>
2021-05-27 10:16:12,841 trestle.utils.fs:104 DEBUG: get contextual model type for input path None
2021-05-27 10:16:12,841 trestle.utils.fs:111 DEBUG: get contextual model type final path /Users/deenine/workspace/compliance-trestle/trestle.workspace/catalogs/mycatalog/catalog/metadata
2021-05-27 10:16:12,842 trestle.utils.fs:119 DEBUG: root_path is /Users/deenine/workspace/compliance-trestle/trestle.workspace and project_model_path is /Users/deenine/workspace/compliance-trestle/trestle.workspace/catalogs/mycatalog
2021-05-27 10:16:12,842 trestle.utils.fs:275 DEBUG: path parts: ['catalog', 'metadata', 'roles']
Traceback (most recent call last):
  File "/Users/deenine/workspace/compliance-trestle/.venv_trestle/bin/trestle", line 33, in <module>
    sys.exit(load_entry_point('compliance-trestle', 'console_scripts', 'trestle')())
  File "/Users/deenine/workspace/compliance-trestle/trestle/cli.py", line 65, in run
    exit(Trestle().run())
  File "/Users/deenine/workspace/compliance-trestle/.venv_trestle/lib/python3.7/site-packages/ilcli/command.py", line 147, in run
    return parsed_args.func(parsed_args, extra_args=extra_args)
  File "/Users/deenine/workspace/compliance-trestle/.venv_trestle/lib/python3.7/site-packages/ilcli/command.py", line 174, in _validate_and_run
    return self._run(parsed_args)
  File "/Users/deenine/workspace/compliance-trestle/trestle/core/commands/split.py", line 104, in _run
    model, element_paths, base_dir, content_type, root_file_name=args_raw[const.ARG_FILE]
  File "/Users/deenine/workspace/compliance-trestle/trestle/core/commands/split.py", line 347, in split_model
    model_obj, element_paths, base_dir, content_type, cur_path_index, split_plan, False, root_file_name
  File "/Users/deenine/workspace/compliance-trestle/trestle/core/commands/split.py", line 185, in split_model_at_path_chain
    element = Element(model_obj)
  File "/Users/deenine/workspace/compliance-trestle/trestle/core/models/elements.py", line 225, in __init__
    raise TrestleError('wrapper_alias is required for a collection type object')
trestle.core.err.TrestleError: wrapper_alias is required for a collection type object
```

**To Reproduce**

1. Clone trestle and check out develop repo at `fc251b9e9c231de67fd214b16bdd7c2a6cb4d3c1` (or head at time of issue creation)
2. Create and activate py3 venv
3. `make develop`
4. Follow [tutorial](https://ibm.github.io/compliance-trestle/tutorials/trestle_sample_workflow/#tutorial-introduction-to-trestle-workflow) and attempt to complete step 5.

**Expected behavior**
Per tutorial step 5.

**Comment by fsuits** [comment]
@deenine thanks for the report - fixed in next release
